services:
  redis:
    hostname: redis
    container_name: redis
    image: redis:6.2.6
    command: redis-server --port 6379
    ports:
      - 6379:6379

  mysql:
    image: mysql:8.0
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: sdpass
      MYSQL_DATABASE: sweetdeal
      MYSQL_USER: sduser
      MYSQL_PASSWORD: sdpass
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
    networks:
      - mynetwork
networks:
  mynetwork:
    driver: bridge